# Generated by Django 5.0.1 on 2024-01-23 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0003_remove_empleados_apellido_materno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planillas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=10)),
                ('anio', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'planillas',
            },
        ),
        migrations.CreateModel(
            name='DetallePlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleados')),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planillas.planillas')),
            ],
            options={
                'db_table': 'detalle_planillas',
            },
        ),
    ]
