# Generated by Django 5.0.1 on 2024-01-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planillas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='planillas',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
