# Generated by Django 5.0.1 on 2024-01-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0001_initial'),
        ('valores', '0002_remove_valores_detalleplanilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleplanillas',
            name='valores',
            field=models.ManyToManyField(blank=True, null=True, to='valores.valores'),
        ),
    ]
