# Generated by Django 5.0.1 on 2024-01-23 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_remove_empleados_apellido_materno_and_more'),
        ('planillas', '0002_planillas_created_at_planillas_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetallePlanilla',
            new_name='DetallePlanillas',
        ),
    ]
