# Generated by Django 5.0.1 on 2024-01-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0003_remove_detalleplanillas_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleplanillas',
            name='total_remuneracion',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='planillas',
            name='anio',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='planillas',
            name='mes',
            field=models.PositiveIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Setiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=1),
        ),
        migrations.AddField(
            model_name='planillas',
            name='suma_sueldo_bruto',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='planillas',
            name='suma_sueldo_neto',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='planillas',
            name='suma_total_afp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='planillas',
            name='suma_total_descuentos',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='planillas',
            name='suma_total_ingresos',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='planillas',
            name='suma_total_remuneracion',
            field=models.FloatField(null=True),
        ),
    ]
