# Generated by Django 5.0.1 on 2024-01-23 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aportaciones', '0003_aportaciones_created_at_aportaciones_updated_at'),
        ('planillas', '0003_rename_detalleplanilla_detalleplanillas'),
    ]

    operations = [
        migrations.AddField(
            model_name='aportaciones',
            name='detallePlanilla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planillas.detalleplanillas'),
        ),
    ]
