# Generated by Django 5.0.1 on 2024-01-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
                ('regimen_laboral', models.CharField(max_length=10)),
                ('categoria_ocupacional', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField()),
                ('remuneracion', models.FloatField()),
                ('estado', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
    ]
