# Generated by Django 5.0.1 on 2024-01-24 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('apellidoPaterno', models.CharField(db_column='apellido_paterno', max_length=20, null=True)),
                ('apellidoMaterno', models.CharField(db_column='apellido_materno', max_length=20, null=True)),
                ('nombres', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
                ('regimenLaboral', models.CharField(db_column='regimen_laboral', max_length=20, null=True)),
                ('categoriaOcupacional', models.CharField(db_column='categoria_ocupacional', max_length=20, null=True)),
                ('cargo', models.CharField(max_length=50)),
                ('fechaIngreso', models.DateField(db_column='fecha_ingreso', null=True)),
                ('remuneracion', models.FloatField()),
                ('estado', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('afp', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='afp.afp')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
    ]
