# Generated by Django 5.0.1 on 2024-01-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_remove_empleados_categoria_ocupacional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='apellido_paterno',
        ),
        migrations.AddField(
            model_name='empleados',
            name='apellidoMaterno',
            field=models.CharField(db_column='apellido_materno', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empleados',
            name='apellidoPaterno',
            field=models.CharField(db_column='apellido_paterno', max_length=20, null=True),
        ),
    ]
