# Generated by Django 5.0.1 on 2024-01-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_remove_empleados_apellidopaterno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='apellidoMaterno',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='categoriaOcupacional',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='fechaIngreso',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='regimenLaboral',
        ),
        migrations.AddField(
            model_name='empleados',
            name='apellido_materno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empleados',
            name='categoria_ocupacional',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empleados',
            name='fecha_ingreso',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='empleados',
            name='regimen_laboral',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
