# Generated by Django 5.0.1 on 2024-01-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planillas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('tipo', models.PositiveIntegerField(choices=[(1, 'INGRESOS'), (2, 'DESCUENTOS'), (3, 'APORTACIONES')], default=1)),
                ('monto', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detallePlanilla', models.ManyToManyField(blank=True, to='planillas.detalleplanillas')),
            ],
            options={
                'db_table': 'valores',
            },
        ),
    ]
