# Generated by Django 5.0.1 on 2024-01-23 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuentos', '0001_initial'),
        ('planillas', '0003_rename_detalleplanilla_detalleplanillas'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuentos',
            name='detallePlanilla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planillas.detalleplanillas'),
        ),
    ]
