# Generated by Django 5.0.1 on 2024-01-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuentos', '0002_descuentos_detalleplanilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuentos',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
