# Generated by Django 5.0.1 on 2024-01-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tasaAportes', models.FloatField(db_column='tasa_aportes', null=True)),
                ('tasaSeguros', models.FloatField(db_column='tasa_seguros', null=True)),
                ('tasaComisionVariable', models.FloatField(db_column='tasa_comision_variable', null=True)),
                ('maxRemuneracion', models.FloatField(db_column='max_remuneracion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'afp',
            },
        ),
    ]
