# Generated by Django 5.0.1 on 2024-01-21 04:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='afp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='afp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
