# Generated by Django 5.0.1 on 2024-01-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afp', '0002_afp_created_at_afp_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afp',
            name='max_remuneracion',
        ),
        migrations.RemoveField(
            model_name='afp',
            name='tasa_aportes',
        ),
        migrations.RemoveField(
            model_name='afp',
            name='tasa_comision_variable',
        ),
        migrations.RemoveField(
            model_name='afp',
            name='tasa_seguros',
        ),
        migrations.AddField(
            model_name='afp',
            name='maxRemuneracion',
            field=models.FloatField(db_column='max_remuneracion', null=True),
        ),
        migrations.AddField(
            model_name='afp',
            name='tasaAportes',
            field=models.FloatField(db_column='tasa_aportes', null=True),
        ),
        migrations.AddField(
            model_name='afp',
            name='tasaComisionVariable',
            field=models.FloatField(db_column='tasa_comision_variable', null=True),
        ),
        migrations.AddField(
            model_name='afp',
            name='tasaSeguros',
            field=models.FloatField(db_column='tasa_seguros', null=True),
        ),
    ]
